FROM php:7.1-fpm-stretch
LABEL maintainer="Christian-Maximilian Steier"

ARG VERSION=18.10
ARG RELEASE=.0

ARG WEB_USER=www-data
ARG WEB_GROUP=www-data
ARG PHP_ROOT_DIR=/usr/local/etc
 
RUN usermod -u 1000 ${WEB_USER} \
 && groupmod -g 1000 ${WEB_GROUP} \
 && sed -i 's*;catch_workers_output = yes*catch_workers_output = yes*g' $PHP_ROOT_DIR/php-fpm.d/www.conf \
 && sed -i 's*;php_flag[display_errors] = off*php_flag[display_errors] = off*g' $PHP_ROOT_DIR/php-fpm.d/www.conf \
 && sed -i 's*;php_admin_flag[log_errors] = on*php_admin_flag[log_errors] = on*g' $PHP_ROOT_DIR/php-fpm.d/www.conf \
 && sed -i 's*;php_admin_value[error_log] = /var/log/fpm-php.www.log*php_admin_value[error_log] = ${PHP_ROOT_DIR}/logs/error.log*g' $PHP_ROOT_DIR/php-fpm.d/www.conf \
 && sed -i 's*listen = 9000*listen = 0.0.0.0:9000*g' $PHP_ROOT_DIR/php-fpm.d/zz-docker.conf

# Scripts
ADD scripts /scripts

# System
RUN /scripts/prepare.sh && \
    /scripts/system_services.sh && \
    /scripts/utilities.sh && \
    /scripts/php-extensions.sh && \
    /scripts/composer.sh

# Mahara
RUN /scripts/mahara.sh

# Copy local files
COPY root/ /
RUN rm -r /etc/services.d/apache

# Cleanup
RUN /scripts/cleanup.sh
ENTRYPOINT ["/init"]
