#!/usr/bin/with-contenv bash
set -e
SERVERNAME=${SERVERNAME:-localhost}
TLS=${TLS:-no}

if [ ! -d /config/mahara ]; then
   mkdir -p /config/mahara
   chown -R www-data:www-data /config/mahara
   chmod g+s,g+w /config/mahara 
fi

if [ -d /etc/apache2 ]; then
  if [ $TLS == "yes" ]; then
    if [ ! -d /config/tls ]; then
      mkdir /config/tls
      chown -R www-data:root /config/tls
    fi
    SUBJECT="/C=DE/ST=Berlin/L=Berlin/O=$SERVERNAME/OU=mahara Server/CN=*"
    if [[ -f /config/tls/cert.key && -f /config/tls/cert.crt ]]; then
      echo "using keys found in /config/tls"
    else
      echo "generating self-signed keys in /etc/apache2/tls, you can replace these with your own keys if required"
      openssl req -new -x509 -days 3650 -nodes -out /config/tls/cert.crt -keyout /config/tls/cert.key -subj "$SUBJECT"
    fi
    sed -i 's*/etc/ssl/certs/ssl-cert-snakeoil.pem*/config/tls/cert.key*g' /etc/apache2/sites-available/default-ssl.conf
    sed -i 's*/etc/ssl/private/ssl-cert-snakeoil.key*/config/tls/cert.crt*g' /etc/apache2/sites-available/default-ssl.conf
    a2ensite default-ssl
  fi
  echo "ServerName $SERVERNAME" > /etc/apache2/conf-available/servername.conf
  a2enconf servername
fi

if [ ! -f /config/mahara/config.php ]; then
   cp /var/www/html/config-dist.php /config/mahara/config.php
   chown -R www-data:www-data /config/mahara/config.php
fi

if [ ! -f /var/www/html/config.php ]; then
   s6-ln -s /config/mahara/config.php /var/www/html/config.php 
fi

exit 0
